# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 11:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0004_auto_20180708_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginentry',
            name='auth_token',
            field=models.CharField(default=b'e57f2dd5-601e-49f6-823d-44b248ed73d4', max_length=512),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 11, 10, 48, 849838)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 11, 10, 48, 848358)),
        ),
    ]
